### ISSUE TITLE
spike: videos

### ISSUE THREAD

**Issue by bo-bok** [ZooeyMiller/anna-freud-hackday-makatalk#24]
goal of spike: to understand how to automatically sequentially play videos in html5 

relates #13

**Comment by ZooeyMiller** [comment]
Have done a bit of research and this code snippet works.
You take all the videos as a nodelist and assign them to the variable 'videos', then loop through, add an event listener to each such that when each video has ended the next video plays.

This now works nicely, the main video plays as soon as the page loads, but we need to work out about loading the videos over the network. I have only used this locally so far, so will need to see how it works when using hosted videos. 
```
<section class="container">
  <video preload='auto' src="cat-short.mp4" type="video/mp4" class="main" autoplay></video>
  <video preload='auto' src="cat-short.mp4" type="video/mp4" class="answer"></video>
  <video preload='auto' src="cat-short.mp4" type="video/mp4" class="answer"></video>
  <video preload='auto' src="cat-short.mp4" type="video/mp4" class="answer"></video>
  <video preload='auto' src="cat-short.mp4" type="video/mp4" class="answer"></video>
</section>

<script>
  const videos = document.querySelectorAll('video');
  videos.forEach((e, i) => {
    e.addEventListener('ended', () => {
      videos[i + 1].play();
    });
});
</script>
```

**Comment by ZooeyMiller** [comment]
We have decided to host the videos on S3, this should work well for the prototype.
